services:
  monitor_mumbai:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - mumbai_monitor_config.env
    command: python monitor.py
    restart: unless-stopped
  baseload_mumbai:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - mumbai_baseload_config.env
    command: python monitor.py
    restart: unless-stopped
  monitor_polygon:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - polygon_monitor_config.env
    command: python monitor.py
    restart: unless-stopped
  baseload_polygon:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - polygon_baseload_config.env
    command: python monitor.py
    restart: unless-stopped
    ports:
        - "12001:8080"